name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Run remote deploy script
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-222-72-204.compute-1.amazonaws.com \
          "bash /opt/subscription-server/install.sh"
