name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up SSH key (NEW)
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY_NEW }}

    - name: Configure known_hosts (pin host key)
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Run remote deploy script
      run: |
        ssh -o UserKnownHostsFile=~/.ssh/known_hosts \
            ubuntu@ec2-13-222-72-204.compute-1.amazonaws.com \
            "bash /opt/subscription-server/install.sh"
